layout_spectrum: 0.7426773
color:
  saturation: 0.3714722
  lightness: 0.2593174
  brandStrength: 0.6133441
  rhythmicContrast: 0.3260918
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
typography_spectrum: 0.4498208
name: ShadowSignalStation
